"""empty message

Revision ID: f61a671a1089
Revises: f1ad62801cbf
Create Date: 2024-12-18 08:34:08.563238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61a671a1089'
down_revision = 'f1ad62801cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('year_of_graduation',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('year_of_graduation',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
